name: Metrics
on:
  # Schedule updates (each hour)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Core
          user: booleans-oss
          config_timezone: Europe/Paris
          committer_message: "update metrics"

          # Display
          template: classic
          base: header, activity, community, repositories

          plugin_isocalendar: yes

          plugin_languages: yes

          plugin_introduction: yes

          plugin_habits: yes

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_lines: yes

          plugin_activity: yes

          plugin_achievements: yes
          plugin_achievements_threshold: B

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKA_TOKEN }}       
